version: 2

jobs:
  e2e_header:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "e2e/package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: | 
            cd e2e
            npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "e2e/package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run --spec "cypress/integration/*/*.spec.js"
      # - run:
      #     name: run e2e header
      #     command: |
      #       cd e2e
      #       npm install
      #       npx cypress run --spec "cypress/integration/header/header.spec.js"
  # e2e_footer:
  #   docker:
  #     - image: cypress/base:8
  #       environment:
  #         ## this enables colors in the output
  #         TERM: xterm
  #     working_directory: ~/app
  #   steps:
  #     - checkout
  #     - run:
  #         name: run e2e footer
  #         command: |
  #           cd e2e
  #           npm install
  #           npx cypress run --spec "cypress/integration/footer/footer.spec.js"
  #           # npx cypress run \
  #           #   --spec "cypress/integration/footer/footer.spec.js" \
  #           #   --config video=false

workflows:
  version: 2
  one_and_two:
    jobs:
      - e2e_header
      # - e2e_footer

# ---------------------------------- Another template ------------------------
# version: 2.1

# commands:
#   build-one:
#     steps:
#       - checkout
#       - run: echo "Hello project"
#       - run: |
#           cd app1
#           node hello.js

#   build-two:
#     steps:
#       - checkout
#       - run: echo "Welcome project"
#       - run: |
#           cd app2
#           node welcome.js

# executors:
#   docker-executor:
#     docker:
#       - image: circleci/node:10.16.0

# jobs:
#   one:
#     executor: docker-executor
#     steps:
#       - build-one
#   two:
#     executor: docker-executor
#     steps:
#       - build-two

# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two:
#           requires:
#             - one
# ---------------------------------- Another template ------------------------
# version: 2
# jobs:
#   one:
#     docker:
#       - image: circleci/node:10.16.02.4.1
#     steps:
#       - checkout
#       - run: echo "Hello project"
#       - run: |
#           cd app1
#           node hello.js
#   two:
#     docker:
#       - image: circleci/node:10.16.0
#     steps:
#       - checkout
#       - run: echo "Welcome project"
#       - run: |
#           cd app2
#           node welcome.js

# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two:
#           requires:
#             - one

# ---------------------------------- Another template ------------------------
# version: 2

# jobs:
#   one:
#     docker:
#       - image: circleci/node:10.16.0
#     steps:
#       - checkout
#       - run: echo "checkout app1"
#       - restore_cache:
#           key: node-v1-{{ .Branch }}-{{ checksum "app1/package-lock.json" }}
#       - run: |
#           cd app1
#           npm install
#       - save_cache:
#           key: node-v1-{{ .Branch }}-{{ checksum "app1/package-lock.json" }}
#           paths:
#             - ~/project
#       - run: |
#           cd app1
#           node hello.js

# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
