version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  one: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/node:10.16.0 # specifically, a docker image with ruby 2.4.1
      # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run: echo "Hello project" # This prints "A first hello" to stdout.
      - run: |
          cd app1
          node hello.js
      # - run: sleep 25 # a command telling the job to "sleep" for 25 seconds.
  two: # This is our second job.
    docker: # it runs inside a docker image, the same as above.
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: echo "Welcome project" # We run a similar echo command to above.
      - run: |
          cd app2
          node welcome.js
      # - run: sleep 15 # and then sleep for 15 seconds.
  # Under the workflows: map, we can coordinate our two jobs, defined above.

workflows:
  version: 2
  one_and_two: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - one
      - two
        requires:
          - one


    #         jobs:
    #   - build
    #   - test:
    #       # start: npm start
    #       # wait-on: 'http://localhost:3000'
    #       requires:
    #         - build # wait for build1 job to complete successfully before starting
    #         # see circleci.com/docs/2.0/workflows/ for more examples.
    # #         build: