version: 2.1

commands:
  build-one:
    steps:
      - checkout
      - run: echo "Hello project"
      - run: |
          cd app1
          node hello.js

  build-two:
    steps:
      - checkout
      - run: echo "Welcome project"
      - run: |
          cd app2
          node welcome.js

executors:
  docker-executor:
    docker:
      - image: circleci/node:10.16.02.4.1 

jobs:
  one:
    executor: docker-executor
    steps:
      - build-one
  two:
    executor: docker-executor
    steps:
      - build-two

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
   


# version: 2
# jobs:
#   one:
#     docker:
#       - image: circleci/node:10.16.02.4.1
#     steps:
#       - checkout
#       - run: echo "Hello project"
#       - run: |
#           cd app1
#           node hello.js
#   two:
#     docker:
#       - image: circleci/node:10.16.0
#     steps:
#       - checkout
#       - run: echo "Welcome project"
#       - run: |
#           cd app2
#           node welcome.js

# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two:
#           requires:
#             - one
   